--- 1. намираме студиата с най-много 3 филма

SELECT DISTINCT NAME, ADDRESS, AVG(LENGTH) AS AVG_LENGTH
FROM STUDIO S 
LEFT JOIN MOVIE ON S.NAME = MOVIE.STUDIONAME
WHERE (SELECT DISTINCT COUNT(*)
       FROM STUDIO JOIN MOVIE ON STUDIO.NAME = MOVIE.STUDIONAME 
       WHERE STUDIO.NAME = S.NAME) <= 3
GROUP BY S.NAME, S.ADDRESS;
