SELECT DISTINCT * FROM STUDIO S
WHERE
EXISTS (SELECT * FROM STUDIO JOIN MOVIE ON S.NAME = MOVIE.STUDIONAME WHERE INCOLOR = 'Y')
AND
EXISTS (SELECT * FROM STUDIO JOIN MOVIE ON S.NAME = MOVIE.STUDIONAME WHERE INCOLOR = 'N')
ORDER BY ADDRESS ASC;


SELECT * FROM STUDIO JOIN MOVIE ON STUDIO.NAME = MOVIE.STUDIONAME;



