SELECT DISTINCT *
FROM MOVIESTAR
JOIN STARSIN ON NAME = STARNAME
JOIN MOVIE ON MOVIETITLE = TITLE;



(SELECT DISTINCT NAME, BIRTHDATE
FROM MOVIESTAR
JOIN STARSIN ON NAME = STARNAME
JOIN MOVIE ON MOVIETITLE = TITLE
WHERE name NOT LIKE '%Jr.%' )
INTERSECT
(SELECT DISTINCT NAME,BIRTHDATE
FROM MOVIESTAR
JOIN STARSIN ON NAME = STARNAME
JOIN MOVIE ON MOVIETITLE = TITLE
AND INCOLOR = 'Y')
ORDER BY BIRTHDATE ASC;

SELECT DISTINCT NAME, BIRTHDATE
FROM MOVIESTAR
JOIN STARSIN ON NAME = STARNAME
JOIN MOVIE ON MOVIETITLE = TITLE
WHERE name NOT LIKE '%Jr.%' AND 
NAME IN (SELECT DISTINCT NAME
FROM MOVIESTAR
JOIN STARSIN ON NAME = STARNAME
JOIN MOVIE ON MOVIETITLE = TITLE
AND INCOLOR = 'Y')
ORDER BY BIRTHDATE ASC;



