SELECT * FROM STUDIO JOIN MOVIE 
ON STUDIONAME = NAME
WHERE NAME LIKE 'M%';


SELECT NAME, MIN(YEAR) AS FST_MOVIE_YEAR, 
MAX(YEAR) AS SND_MOVIE_YEAR, COUNT(TITLE) AS MOVIE_CNT
FROM STUDIO JOIN MOVIE ON NAME=STUDIONAME
WHERE NAME LIKE 'M%'
GROUP BY NAME;
