
CREATE TABLE PRODUCT (
 MODEL VARCHAR(255) NOT NULL,
 MAKER VARCHAR(255),
 TYPE CHAR(8)
);

CREATE TABLE LAPTOP (
 CODE CHAR(30) NOT NULL,
 MODEL VARCHAR(255) NOT NULL,
 SPEED INT, 
 RAM INT,
 HD INT,
 PRICE INT,
 SCREEN INT
);

CREATE TABLE PC (
 CODE CHAR(30) NOT NULL,
 MODEL VARCHAR(255) NOT NULL,
 SPEED INT, 
 RAM INT,
 HD INT,
 CD INT,
 PRICE INT
);

CREATE TABLE PRINTER (
   CODE CHAR(30) NOT NULL,
   MODEL VARCHAR(255) NOT NULL,
   PRICE INT, 
   COLOR CHAR(1),
   TYPE CHAR(8)
);


ALTER TABLE PRODUCT ADD CONSTRAINT PK_PRODUCT PRIMARY KEY(MODEL);

ALTER TABLE PC ADD CONSTRAINT PK_PC PRIMARY KEY(CODE);
ALTER TABLE PC ADD CONSTRAINT FK_PC_MODEL FOREIGN KEY(MODEL) REFERENCES PRODUCT(MODEL);

ALTER TABLE LAPTOP ADD CONSTRAINT PK_LAPTOP PRIMARY KEY(CODE);
ALTER TABLE LAPTOP ADD CONSTRAINT FK_LAPTOP_MODEL FOREIGN KEY(MODEL) REFERENCES PRODUCT(MODEL);

ALTER TABLE PRINTER ADD CONSTRAINT PK_PRINTER PRIMARY KEY(CODE);
ALTER TABLE PRINTER ADD CONSTRAINT FK_PRINTER_MODEL FOREIGN KEY(MODEL) REFERENCES PRODUCT(MODEL);

